Repository hybridapp-io/ham-placement, pull requests merged in 2020-09, with the labels that each got.

#5 update operator version to 0.18.0
  go.mod
  go.sum
  pkg/controller/placementrule/candidate.go
Labels: approved, lgtm, size/XL

#6 Add the deployer type candidate
  go.mod
  go.sum
  pkg/controller/placementrule/candidate.go
  pkg/controller/placementrule/decisionmaker.go
Labels: approved, lgtm, size/S

#7 Circular dep
  deploy/crds/core.hybridapp.io_deployers_crd.yaml
  deploy/crds/core.hybridapp.io_placementrules_crd.yaml
  go.mod
  go.sum
  pkg/apis/apis.go
  pkg/apis/core/v1alpha1/deployer_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/placementrule/candidate.go
Labels: lgtm, size/XXL

#8 ScoredObjectReference
  OWNERS
  deploy/crds/core.hybridapp.io_placementrules_crd.yaml
  pkg/advisor/alphabet/alphabet_advisor.go
  pkg/advisor/alphabet/alphabet_controller.go
  pkg/advisor/utils/utils.go
  pkg/advisor/veto/veto_advisor.go
  pkg/advisor/veto/veto_controller.go
  pkg/apis/core/v1alpha1/placementrule_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/placementrule/decisionmaker.go
Labels: approved, lgtm, size/L

#9 added deployerset_types
  deploy/crds/core.hybridapp.io_deployersets_crd.yaml
  pkg/apis/core/v1alpha1/deployerset_types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L
