Repository hybridapp-io/ham-placement, pull requests merged in 2020-11, with the labels that each got.

#13 Update Dockerfile
  build/Dockerfile
Labels: approved, lgtm, size/S

#14 added unit tests for scored/unscored recom.
  pkg/apis/core/v1alpha1/placementrule_types.go
  pkg/controller/placementrule/candidate.go
  pkg/controller/placementrule/decisionmaker.go
  pkg/controller/placementrule/placementrule_controller_test.go
Labels: approved, lgtm, size/XL

#15 Add bucket 2 placementrule tests
  pkg/controller/placementrule/placementrule_controller_test.go
Labels: approved, lgtm, size/L

#17 additional logging
  pkg/controller/placementrule/candidate.go
Labels: approved, lgtm, size/XS
